name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      IMAGETAG:
        description: 'Image Tag'
        required: true
        default: '1'
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
          - functional
          - integration
          - regression
          - uat
          - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Checkout same GitHub repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 🔹 Update deployment.yml
      - name: Update Image Tag
        run: |
          cd ${{ github.event.inputs.environment }}
          sed -i 's|image: .*|image: dikshat1024/democicd:${{ github.event.inputs.IMAGETAG }}|g' deployment.yml

      # 🔹 Commit changes
      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "New deployment for Build ${{ github.event.inputs.IMAGETAG }}" || echo "No changes"

      # 🔹 Push changes (no password needed)
      - name: Push Changes
        run: |
          git push origin HEAD:main
